### ISSUE TITLE
Update docs (DTC snippets.md) to explain how to use custom functions

### ISSUE THREAD

**Issue by roy100** [productml/blurr#226] opened 2018-04-19 16:24 UTC
**I certify I'm including:**

- [ ] A descriptive title
- [ ] A description of the problem I'm trying to solve, including *why* I think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why my solution is better

Docs need to be updated as a result of #58

**Comment by prashastk** [comment] 2018-04-19 16:32
Duplicate of #208

**Closed by prashastk** 2018-04-19 16:32 UTC
