### ISSUE TITLE
Support out-of-order time-series events for Activity Aggregate

### ISSUE THREAD

**Issue by indradeep** [productml/blurr#215] opened 2018-04-18 09:38 UTC
The Activity Aggregate currently expects events to arrive in order.  If events arrive out of order, it currently breaks the chain of sessions created.

Once the store normalization #187 is complete, the incorporate the new store APIs to build the out-of-order support.

**Comment by prashastk** [comment] 2018-04-23 23:25
Duplicate of #179

**Closed by prashastk** 2018-04-23 23:25 UTC
Labels: enhancement
